// <auto-generated />
using HM.Cloud;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
namespace HM.Cloud.Migrations
{
    [DbContext(typeof(CloudDbContext))]
    partial class CloudDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
            modelBuilder.Entity("HM.Cloud.SoftVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("AddUser")
                        .HasMaxLength(128);
                    b.Property<string>("Changelog");
                    b.Property<DateTime>("CreationTime");
                    b.Property<DateTime?>("LastModificationTime");
                    b.Property<bool>("Mandatory");
                    b.Property<string>("SoftName")
                        .IsRequired()
                        .HasMaxLength(32);
                    b.Property<string>("UpdateUser")
                        .HasMaxLength(128);
                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(128);
                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32);
                    b.HasKey("Id");
                    b.ToTable("SoftVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
